name: Deploy to server


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:
      
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: |
            yarn install 
           # yarn run dev

  Deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-cli@v2
      id: netlify
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './next'
        comment-on-commit: true